nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE', 'PATCH']
    paths:
        '^/': ~
