version: "3.9"

services:
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        volumes:
            - ./:/var/www/html:cached
            - ~/.composer:/tmp/composer-cache
        environment:
            APP_ENV: dev
            COMPOSER_CACHE_DIR: /tmp/composer-cache
        depends_on:
            postgres:
                condition: service_healthy

    nginx:
        image: nginx:stable-alpine
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html:ro
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    postgres:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U symfony -d app"]
            interval: 5s
            timeout: 3s
            retries: 10

volumes:
    db_data:
